# Netlify configuration file

[build]
  # Build command (runs from root, builds frontend)
  command = "npm run build"
  # Directory where the build output is located
  publish = "colorsense/build/"

# Environment variables for production
[build.environment]
  NODE_ENV = "production"
  VITE_NODE_ENV = "production"
  VITE_API_BASE_URL = "https://colorsense-backend.onrender.com"
  VITE_API_VERSION = "v1"
  VITE_APP_NAME = "ColorSense"
  VITE_APP_VERSION = "1.0.0"
  VITE_ENABLE_AI_CHAT = "true"
  VITE_ENABLE_WISHLIST = "true"
  VITE_ENABLE_CART = "true"
  VITE_ENABLE_USER_REVIEWS = "true"

# Redirect rules for Single Page Application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
